### ISSUE TITLE
Como adicionar um usuário em um projeto?

### ISSUE THREAD

**Issue by rafaelsamenezes** [KanbanEng2/kanban#12]

**Comment by rodrigost23** [comment]
Acho que precisa ter configurações do projeto.

**Comment by rafaelsamenezes** [comment]
Pode ser um botão na navigation bar? Tipo os quadrados rosa na imagem

![rect4210](https://cloud.githubusercontent.com/assets/8601807/23833005/e66f2610-0715-11e7-8079-533c24652b8c.png)

**Comment by rodrigost23** [comment]
Pode ser, mas acho que seria mais fácil só adicionar um item no menu onde tem o filtro, mas adicioná-lo no overflow. Mas se você souber como adicionar um botão aí  onde você sugeriu sem ter muito trabalho, show.
