### ISSUE TITLE
Atualizar tasks da main activity para o projeto selecionado

### ISSUE THREAD

**Issue by rafaelsamenezes** [KanbanEng2/kanban#14]

**Comment by rodrigost23** [comment]
Só atualizar as 3 listas, ou usar fragments?

**Comment by rafaelsamenezes** [comment]
Acho que o ideal seria colocar as 3 listas dentro do fragment

**Comment by rodrigost23** [comment]
Sim, mas mudaria o fragment pra cada projeto, então? Seria útil assim, pois daria pra criar um fragment já com parâmetro indicando qual o projeto. E quando mudasse de projeto, não precisaria destruir o fragment.

**Comment by rafaelsamenezes** [comment]
Acho que tem que destruir, cada fragment vai ter uma conexão aberta com o banco, o que eu acho que vai aumentar o consumo de bateria e memória (a n ser que o Firebase gerencie tudo isso automaticamente)

**Comment by rodrigost23** [comment]
Dá pra fechar a conexão com o banco no "pause" do fragment e reconectar no "resume". Não lembro se são esses os nomes, mas não precisaria destruir assim.
