### ISSUE TITLE
Criar uma tela de "nenhum projeto selecionado"

### ISSUE THREAD

**Issue by rodrigost23** [KanbanEng2/kanban#15]

**Comment by rodrigost23** [comment]
Opções:
- Manter a nav drawer exibida até o usuário escolher um projeto
- Mostrar a lista de projetos
- Ou mostrar só uma instrução de "selecione um projeto no painel lateral"

**Comment by rafaelsamenezes** [comment]
Acho que não rola manter a nav drawer e nem mostrar a lista de projetos,  porque vai mostrar que é tudo carregado na hora e do nada (podemos adicionar uma progress bar)
Acho que o selecione um projeto no painel lateral... e seria bom se na primeira vez aparecesse aquele "tutorial" apontando pra onde clicar
