### ISSUE TITLE
Utilizar TaskActivity para edição de tarefas

### ISSUE THREAD

**Issue by rafaelsamenezes** [KanbanEng2/kanban#8]

**Comment by rodrigost23** [comment]
Não esqueça de resgatar [a animação de transição](../blob/5f738f37091c0d85960987d4cf54421c6fa2c7e9/app/src/main/java/br/ufrr/eng2/kanban/MainActivity.java#L74-L86)

**Comment by rafaelsamenezes** [comment]
Já adicionei

**Comment by rafaelsamenezes** [comment]
O problema é que a animação anterior por algum motivo usa roxo como padrão...

**Comment by rodrigost23** [comment]
Tem que mudar o background do elemento `R.id.toolbar_background` em algum dos eventos na TaskActivity.
